### ISSUE TITLE
missing module when deploying

### ISSUE THREAD

**Issue by hatoyski** [Manssizz/CendrawasihLeech#7]
2021-12-04T02:23:48.320693+00:00 app[worker.1]: Traceback (most recent call last):
2021-12-04T02:23:48.320696+00:00 app[worker.1]:   File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
2021-12-04T02:23:48.320696+00:00 app[worker.1]:     return _run_code(code, main_globals, None,
2021-12-04T02:23:48.320696+00:00 app[worker.1]:   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
2021-12-04T02:23:48.320699+00:00 app[worker.1]:     exec(code, run_globals)
2021-12-04T02:23:48.320699+00:00 app[worker.1]:   File "/CendrawasihLeech/tobrot/__main__.py", line 47, in <module>
2021-12-04T02:23:48.320699+00:00 app[worker.1]:     from tobrot.helper_funcs.download import down_load_media_f
2021-12-04T02:23:48.320700+00:00 app[worker.1]:   File "/CendrawasihLeech/tobrot/helper_funcs/download.py", line 19, in <module>
2021-12-04T02:23:48.320700+00:00 app[worker.1]:     from tobrot.helper_funcs.upload_to_tg import upload_to_gdrive
2021-12-04T02:23:48.320700+00:00 app[worker.1]:   File "/CendrawasihLeech/tobrot/helper_funcs/upload_to_tg.py", line 17, in <module>
2021-12-04T02:23:48.320700+00:00 app[worker.1]:     from hachoir.metadata import extractMetadata
2021-12-04T02:23:48.320701+00:00 app[worker.1]: ModuleNotFoundError: No module named 'hachoir'
2021-12-04T02:23:48.714723+00:00 heroku[worker.1]: Process exited with status 1
2021-12-04T02:23:48.785337+00:00 heroku[worker.1]: State changed from up to crashed

**Comment by Manssizz** [comment]
fixed
